# Generated by Django 5.0.3 on 2024-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_event_eventparticipation_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coach_type',
            field=models.CharField(blank=True, choices=[('head_coach', 'Head Coach'), ('assistant_coach', 'Assistant Coach'), ('goalkeeping_coach', 'Goalkeeping Coach'), ('fitness_coach', 'Fitness Coach')], max_length=20, null=True),
        ),
    ]
