# Generated by Django 5.0.3 on 2024-03-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_profile_coach_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coach_type',
            field=models.CharField(blank=True, choices=[('cricket', 'Cricket_coach'), ('football', 'Football_coach'), ('goalkeeping_coach', 'Goalkeeping Coach'), ('fitness_coach', 'Fitness Coach')], max_length=20, null=True),
        ),
    ]
